###
get http://localhost:4000/

###
get http://localhost:4000/user/
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOiI5ODAzOSIsIm5tdXNlciI6IkFndXMgU3VuYXJ0byIsImlkdXNlcmdyb3VwIjoiMTAwOzAwMjswMDQ7MDIwIiwiaWF0IjoxNjgyOTQ3NzExLCJleHAiOjE2ODI5NDc5MTF9.Ix63k26iH7figLmt2q5KuBVrKNQnY3COMbBFYJPP4Jo

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "iduser":"msib_nisa",
    "password":"123",
    "thang":"2023"
}

###
GET http://localhost:4000/login/getAllUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOiI5ODAzOSIsIm5tdXNlciI6IkFndXMgU3VuYXJ0byIsImlkdXNlcmdyb3VwIjoiMTAwOzAwMjswMDQ7MDIwIiwiaWF0IjoxNjg0MTIzMjQ0LCJleHAiOjE2ODQxMjMyNjR9.A4Lh5DjDVczpsWhOmjY1XbihlkXizQVuTMn-NiRwliw

###
GET http://localhost:4000/login/refreshToken


###
DELETE http://localhost:4000/login/logout


###
GET http://localhost:4000/ruangRapat/getRuangRapats

###
POST http://localhost:4000/ruangRapat/insertRuangRapat
Content-Type: application/json

{
    "data":{
        "nmrapat":"coba",
        "letak":"Lantai 201"
        }
}
